<div id="announcements">
    <% foreach $announcements as $announcement %>
    <div class="announcement">
        <section>
            <hgroup>
              <h1 class="title"><% $announcement->title|escape %></h1>
              <p class="date"><% $announcement->createDateTime|date_format:'%Y-%m-%d' %></p>
            </hgroup>
            <div class="content"><% $announcement->content %></div>
        </section>
    </div>
    <% /foreach %>
</div>
