<div id="location">
    <section>
        <header>
            <h1>會場地點</h1>
        </header>
        <p><% $conference->location|escape %>（<a href="http://maps.google.com/maps?q=<% $conference->address|escape %>"><% $conference->address|escape %></a>）</p>
        <iframe width="100%" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://goo.gl/p8DxP"></iframe>
    </section>
    <section>
        <header>
            <h1>交通資訊</h1>
        </header>
        <% $conference->traffic %>
    </section>
</div>