<!doctype html>
<html class="no-js" lang="zh-TW">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=0;" />
        <link href="<% $this->baseUrl() %>/img/apple-touch-icon.png" rel="apple-touch-icon" />
        <link rel="stylesheet" href="<% $this->baseUrl() %>/css/mobile.css" media="handheld, screen" />
        <title>PHPConf Taiwan <% $conference->year %></title>
    </head>
    <body>
        <h1 id="pageTitle"></h1>
        <a class="button" href="#menu" id="homeButton">主選單</a>
        <ul class="menu" id="menu" title="PHPConf Taiwan 2011" selected="true">
            <li><a href="#announcements" class="toPanel">公告</a></li>
            <li><a href="#sessions" class="toPanel">議程</a></li>
            <li><a href="#location" class="toPanel">地點</a></li>
            <li><a href="http://www.openfoundry.org/tw/activities/details/170">報名</a></li>
            <li><a href="http://twpug.net/modules/newbb/viewforum.php?forum=41">討論區</a></li>
        </ul>
        <div id="announcements" class="panel" title="公告">
            <% foreach $announcements as $announcement %>
            <div class="announcement">
                <section>
                    <header>
                        <h1><% $announcement->title|escape %></h1>
                    </header>
                    <div class="content"><% $announcement->content %></div>
                </section>
            </div>
            <% /foreach %>
        </div>
        <div id="sessions" class="panel" title="議程">
            <section>
                <header>
                    <h1>議程介紹</h1>
                </header>

                <table>
                    <tr>
                        <th class="time">時間</th>
                        <th class="session">議程</th>
                    </tr>
                    <% foreach $sessions as $session %>
                    <% if null === $session->talker %>
                    <tr class="break">
                        <td colspan="2">
                            <% $session->subject|escape %> (<% $session->startTime|escape %> ~ <% $session->endTime|escape %>)
                        </td>
                    </tr>
                    <% else %>
                    <tr class="info">
                        <td class="time"><span class="startTime"><% $session->startTime|escape %></span> ~ <span class="endTime"><% $session->endTime|escape %></span></td>
                        <td>
                            <section>
                                <hgroup>
                                    <h1 class="subject"><% $session->subject|escape %></h1>
                                    <h2 class="talker"><% $session->talker|escape %></h2>
                                </hgroup>
                                <div class="brief"><% $session->brief %></div>
                            </section>
                        </td>
                    </tr>
                    <% /if %>
                    <% /foreach %>
                </table>
            </section>
        </div>
        <div id="location" class="panel" title="地點">
            <section>
                <header>
                    <h1>會場地點</h1>
                </header>
                <p><% $conference->location|escape %>（<a href="http://maps.google.com/maps?q=<% $conference->address|escape %>"><% $conference->address|escape %></a>）</p>
                <iframe width="100%" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://goo.gl/p8DxP"></iframe>
            </section>
            <section>
                <header>
                    <h1>交通資訊</h1>
                </header>
                <% $conference->traffic %>
            </section>
        </div>
        <script type="application/x-javascript" src="<% $this->baseUrl() %>/js/jquery-1.6.4.min.js"></script>
        <script type="application/x-javascript" src="<% $this->baseUrl() %>/js/mobile.js"></script>
    </body>
</html>