<!doctype html>
<html class="no-js" lang="zh-TW">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=0;" />
        <link href="<% $this->baseUrl() %>/img/apple-touch-icon.png" rel="apple-touch-icon" />
        <link rel="stylesheet" href="<% $this->baseUrl() %>/css/mobile.css" media="handheld, screen" />
        <title>PHPConf Taiwan <% $conference->year %></title>
    </head>
    <body>
        <div id="header"><h1>PHPConf Taiwan <% $conference->year %></h1></div>
		<div id="container">
			<div id="content">
				<ul>
					<li><span rel="#">I</span></li>
					<li><span rel="#">Am</span></li>

					<li><span rel="#">A</span></li>
					<li><span rel="#">Long</span></li>
					<li><span rel="#">List</span></li>
					<li><span rel="#">Of</span></li>
					<li><span rel="http://google.com">Nothing</span></li>
					<li><span rel="#">In</span></li>

					<li><span rel="#">Particular</span></li>
					<li><span rel="#">This</span></li>
					<li><span rel="#">Is</span></li>
					<li><span rel="#">A</span></li>
					<li><span rel="#">Fixed</span></li>
					<li><span rel="#">Positioning</span></li>

					<li><span rel="#">Test</span></li>
					<li><span rel="#">I</span></li>
					<li><span rel="#">Am</span></li>
					<li><span rel="#">A</span></li>
					<li><span rel="#">Long</span></li>
					<li><span rel="#">List</span></li>

					<li><span rel="#">Of</span></li>
					<li><span rel="http://google.com">Nothing</span></li>
					<li><span rel="#">In</span></li>
					<li><span rel="#">Particular</span></li>
					<li><span rel="#">This</span></li>
					<li><span rel="#">Is</span></li>

					<li><span rel="#">A</span></li>
					<li><span rel="#">Fixed</span></li>
					<li><span rel="#">Positioning</span></li>
					<li><span rel="#">Test</span></li>
				</ul>
			</div>
		</div>

		<div id="footer">
			<ul>
				<li class="team"><a href="#team">Team</span></li>
				<li class="feed"><span>Feed</span></li>
				<li class="post"><span>Post</span></li>
				<li class="box"><span>Box</span></li>
				<li class="games"><span>Games</span></li>

			</ul>
		</div>
        <%*
        <ul id="menu" title="PHPConf Taiwan 2011">
            <li><a href="#announcements" class="toPanel selected">公告</a></li>
            <li><a href="#sessions" class="toPanel">議程</a></li>
            <li><a href="#location" class="toPanel">地點</a></li>
            <li><a href="http://www.openfoundry.org/tw/activities/details/170">報名</a></li>
            <li><a href="http://twpug.net/modules/newbb/viewforum.php?forum=41">討論區</a></li>
        </ul>
        <div id="container">
            <h1 id="pageTitle">PHPConf Taiwan 2011</h1>
            <div id="announcements" class="panel selected" title="公告">
                <% foreach $announcements as $announcement %>
                <div class="block">
                    <h1><% $announcement->title|escape %></h1>
                    <div class="content"><% $announcement->content %></div>
                </div>
                <% /foreach %>
            </div>
            <div id="sessions" class="panel" title="議程">
                <ul class="block">
                    <% foreach $sessions as $session %>
                    <li <% if null !== $session->talker %>class="<% cycle values="alt," %>"<% else %>class="break"<% /if %>>
                        <p>
                            <span class="subject"><% $session->subject|escape %></span>
                            <span class="startTime"><% $session->startTime|escape %></span>
                            ~
                            <span class="endTime"><% $session->endTime|escape %></span>
                            <% if null !== $session->talker %>
                            <span class="talker"><% $session->talker|escape %></span>
                            <% /if %>
                        </p>
                        <div class="brief"><% $session->brief %></div>
                    </li>
                    <% /foreach %>
                </ul>
            </div>
            <div id="location" class="panel" title="會場地點">
                <div class="block">
                    <p><% $conference->location|escape %>（<a href="http://maps.google.com/maps?q=<% $conference->address|escape %>"><% $conference->address|escape %></a>）</p>
                    <% $conference->traffic %>
                    <iframe width="100%" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" data-src="<% $conference->mapUrl|escape %>"></iframe>
                </div>
            </div>
        </div>
        *%>
        <script type="application/x-javascript" src="<% $this->baseUrl() %>/js/jquery-1.6.4.min.js"></script>
        <script type="application/x-javascript" src="<% $this->baseUrl() %>/js/jquery.bullseye-1.0-min.js"></script>
        <script type="application/x-javascript" src="<% $this->baseUrl() %>/js/mobile.js"></script>
    </body>
</html>