<!doctype html>
<html class="no-js" lang="zh-TW">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=0;" />
        <link href="<% $this->baseUrl() %>/img/apple-touch-icon.png" rel="apple-touch-icon" />
        <link rel="stylesheet" href="<% $this->baseUrl() %>/css/mobile.css" media="handheld, screen" />
        <title>PHPConf Taiwan <% $conference->year %></title>
    </head>
    <body>
        <% $pages = ['announcements', 'sessions', 'location'] %>

        <% foreach $pages as $pageId %>
        <div data-role="page" id="<% $pageId %>">
            <% partial name="index/mobile/layout/header" %>
            <% partial name="index/mobile/layout/nav" id=$pageId %>
            <% partial name="index/mobile/page/$pageId" %>
            <% partial name="index/mobile/layout/footer" %>
        </div>
        <% /foreach %>

        <script type="application/x-javascript" src="<% $this->baseUrl() %>/js/jquery-1.6.4.min.js"></script>
        <script type="application/x-javascript" src="<% $this->baseUrl() %>/js/jquery.mobile-1.0rc1.min.js"></script>
    </body>
</html>