<?xml version="1.0" encoding="UTF-8" ?>
<oembed>
  <version><% $version %></version>
  <type><% $type %></type>
  <title><% $title %></title>
  <thumbnail_url><% $thumbnail_url %></thumbnail_url>
  <thumbnail_width><% $thumbnail_width %></thumbnail_width>
  <thumbnail_height><% $thumbnail_height %></thumbnail_height>
  <author_name><% $author_name %></author_name>
  <author_url><% $author_url %></author_url>
  <provider_name><% $provider_name %></provider_name>
  <provider_url><% $provider_url %></provider_url>
</oembed>
