<div id="sessions" class="panel" title="議程">
    <section>
        <header>
            <h1>議程介紹</h1>
        </header>
        <table>
            <tr>
                <th class="time">時間</th>
                <th class="session">議程</th>
            </tr>
            <% foreach $sessions as $session %>
            <% if null === $session->talker %>
            <tr class="break">
                <td colspan="2">
                    <% $session->subject|escape %> (<% $session->startTime|escape %> ~ <% $session->endTime|escape %>)
                </td>
            </tr>
            <% else %>
            <tr class="info">
                <td class="time"><span class="startTime"><% $session->startTime|escape %></span> ~ <span class="endTime"><% $session->endTime|escape %></span></td>
                <td>
                    <section>
                        <hgroup>
                            <h1 class="subject"><% $session->subject|escape %></h1>
                            <h2 class="talker"><% $session->talker|escape %></h2>
                        </hgroup>
                        <div class="brief"><% $session->brief %></div>
                    </section>
                </td>
            </tr>
            <% /if %>
            <% /foreach %>
        </table>
    </section>
</div>