<aside>
    <div class="section">
        <section>
            <header>
                <h1>贊助</h1>
            </header>

            <dl>
            <% foreach $sponsors as $sponsor %>
                <dt><% $sponsor->supply|escape %></dt>
                <dd><% if $sponsor->url %><a href="<% $sponsor->url|escape %>"><% $sponsor->name|escape %></a><% else %><span><% $sponsor->name|escape %><% /if %></span></dd>
            <% /foreach %>
            </dl>

        </section>
    </div>
</aside>