<aside>
    <div class="section">
        <section>
            <header>
                <h1>贊助</h1>
            </header>

            <dl>
            <% foreach $sponsors as $sponsor %>
                <dt><% $sponsor->supply|escape %></dt>
                <dd>
                    <% if $sponsor->url %>
                    <a href="<% $sponsor->url|escape %>">
                    <% /if %>
                    <% if $sponsor->logoUrl %>
                    <img src="<% $sponsor->logoUrl|escape %>" alt="<% $sponsor->name|escape %>" />
                    <% else %>
                    <span><% $sponsor->name|escape %></span>
                    <% /if %>
                    <% if $sponsor->url %>
                    </a>
                    <% /if %>
                </dd>
            <% /foreach %>
            </dl>

        </section>
    </div>
</aside>