<!doctype html>
<html class="no-js" lang="zh-TW">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title>PHPConf Taiwan <% $year %></title>
        <meta name="description" content="" />
        <meta name="author" content="" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <link rel="shortcut icon" href="<% $this->baseUrl() %>/favicon.gif" />
        <link rel="stylesheet" href="<% $this->baseUrl() %>/css/admin.css" media="screen, projection" />
        <link rel="stylesheet" href="<% $this->baseUrl() %>/css/print.css" media="print" />
        <!--[if IE]>
            <link href="<% $this->baseUrl() %>/css/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
        <![endif]-->
        <!--[if lt IE 7]>
            <link href="<% $this->baseUrl() %>/css/ie6.css" media="screen, projection" rel="stylesheet" type="text/css" />
        <![endif]-->
        <script src="<% $this->baseUrl() %>/lib/modernizr-2.0.6.min.js"></script>
    </head>
    <body>
        <div id="container">
            <header>
                <hgroup>
                    <h1>PHPConf Taiwan <% $year %></h1>
                    <h2>管理介面</h2>
                </hgroup>
            </header>
            <% if $currentAdmin %>
            <nav>
                <ul>
                    <li><a href="<% $this->url(['action' => 'conferences']) %>">年度會議</a></li>
                    <li><a href="<% $this->url(['action' => 'index']) %>">公告</a></li>
                    <li><a href="<% $this->url(['action' => 'sessions']) %>">議程</a></li>
                    <li><a href="<% $this->url(['action' => 'staffs']) %>">工作人員</a></li>
                    <li><a href="<% $this->url(['action' => 'jobs']) %>">工作名稱</a></li>
                    <li><a href="<% $this->url(['action' => 'sponsors']) %>">贊助單位</a></li>
                    <li><a href="<% $this->url(['action' => 'logout']) %>">登出</a></li>
                </ul>
            </nav>
            <% /if %>
            <div id="main" role="main">
                <% $this->layout()->content %>
            </div>
        </div> <!--! end of #container -->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="<% $this->baseUrl() %>/lib/jquery-1.6.2.min.js"><\/script>')</script>
        <script src="<% $this->baseUrl() %>/js/phpconf.js"></script>
    </body>
</html>
