<!doctype html>
<html class="no-js" lang="zh-TW">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title>PHPConf Taiwan <% $year %></title>
        <meta name="description" content="" />
        <meta name="author" content="" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />

        <link rel="stylesheet" href="<% $this->baseUrl() %>/css/layout.css" media="screen, projection" />
        <link rel="stylesheet" href="<% $this->baseUrl() %>/css/style.css" media="screen, projection" />
        <link rel="stylesheet" href="<% $this->baseUrl() %>/css/print.css" media="print" />
        <!--[if IE]>
            <link href="<% $this->baseUrl() %>/css/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
        <![endif]-->
        <!--[if lt IE 7]>
            <link href="<% $this->baseUrl() %>/css/ie6.css" media="screen, projection" rel="stylesheet" type="text/css" />
        <![endif]-->
        <script src="<% $this->baseUrl() %>/lib/modernizr-2.0.6.min.js"></script>
    </head>
    <body>
        <div id="container">
            <header>
                <hgroup>
                    <h1>PHPConf Taiwan <% $year %></h1>
                    <h2>台灣 PHP </h2>
                </hgroup>

            </header>
            <nav>
                <ul>
                    <li><a href="#">報名</a></li>
                    <li><a href="#">議程</a></li>
                    <li><a href="#">地點</a></li>
                    <li><a href="#">關於 PHPConf Taiwan</a></li>
                </ul>
            </nav>
            <% $this->layout()->content %>
            <aside>
                <section></section>
                <section></section>
                <section></section>
                <section></section>
                <section></section>
            </aside>
            <footer>
                <p class="copyright">&copy;<% $year %> PHPConf.TW</p>
            </footer>
        </div> <!--! end of #container -->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/libs/jquery-1.6.2.min.js"><\/script>')</script>
        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']]; // Change UA-XXXXX-X to be your site's ID
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
                g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
                s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>
