<!doctype html>
<html class="no-js" lang="zh-TW">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="description" content="" />
        <meta name="author" content="jaceju" />
        <meta name="og_title" property="og:title" content="PHPConf Taiwan 2011" />
        <meta name="og_type" property="og:type" content="article" />
        <meta name="og_url" property="og:url" content="http://phpconf.tw/2011" />
        <meta name="og_image" property="og:image" content="http://phpconf.tw/img/logo/phpconf.jpg" />
        <meta name="og_site_name" property="og:site_name" content="PHPConf Taiwan" />
        <link rel="alternate" type="application/json+oembed" href="http://phpconf.tw/<% $conference->year %>/oembed/?format=json" title="PHPConf Taiwan oEmbed Profile" />
        <link rel="alternate" type="text/xml+oembed" href="http://phpconf.tw/<% $conference->year %>/oembed/?format=xml" title="PHPConf Taiwan oEmbed Profile" />
        <title>PHPConf Taiwan <% $conference->year %></title>
        <link rel="shortcut icon" href="<% $this->baseUrl() %>/favicon.gif" />
        <link rel="stylesheet" href="<% $this->baseUrl() %>/css/<% $conference->year %>.css" media="screen, projection" />
        <link rel="stylesheet" href="<% $this->baseUrl() %>/css/print.css" media="print" />
        <!--[if IE]>
            <link href="<% $this->baseUrl() %>/css/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
        <![endif]-->
        <!--[if lt IE 7]>
            <link href="<% $this->baseUrl() %>/css/ie6.css" media="screen, projection" rel="stylesheet" type="text/css" />
        <![endif]-->
        <script src="<% $this->baseUrl() %>/lib/modernizr-2.0.6.min.js"></script>
    </head>
    <body>
        <div id="container">
            <div id="header">
                <header class="page">
                    <div id="hgroup">
                        <hgroup>
                            <h1><a href="<% $this->baseUrl() %>">PHPConf Taiwan <% $conference->year %></a></h1>
                            <h2>台灣 PHP 界的大盛事</h2>
                            <% if $conference->registrable() %>
                            <h3><a class="register" href="<% $conference->registrationUrl|escape %>" target="_blank">現在就報名！</a></h3>
                            <% else %>
                            <h3 class="registration-time">報名時間︰ 10/21 (五) 下午 01:30 ，報名人數︰ 100 人。</h3>
                            <% /if %>
                        </hgroup>
                    </div>
                </header>
                <% partial name="frontend/nav" class="top" %>
            </div>
            <div id="body">
                <div id="main" role="main">
                    <% $this->layout()->content %>
                </div>
                <%*
                <div id="aside">
                    <% partial name="frontend/aside" %>
                </div>
                *%>
            </div>
            <div id="footer">
                <footer class="page">
                    <p class="powered"><a href="http://framework.zend.com">Powered By Zend Framework</a></p>
                    <p class="copyright">&copy;<% $year %> PHPConf.TW</p>
                </footer>
                <% partial name="frontend/nav" class="bottom" %>
            </div>
        </div> <!--! end of #container -->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="<% $this->baseUrl() %>/lib/jquery-1.6.2.min.js"><\/script>')</script>
        <script src="<% $this->baseUrl() %>/js/phpconf.js"></script>
        <!-- <% date('Y-m-d H:i:s') %> -->
    </body>
</html>
