<!doctype html>
<html class="no-js" lang="zh-TW">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title>PHPConf Taiwan <% $year %></title>
        <meta name="description" content="" />
        <meta name="author" content="" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <link rel="shortcut icon" href="<% $this->baseUrl() %>/favicon.gif" />
        <link rel="stylesheet" href="<% $this->baseUrl() %>/css/style.css" media="screen, projection" />
        <link rel="stylesheet" href="<% $this->baseUrl() %>/css/print.css" media="print" />
        <!--[if IE]>
            <link href="<% $this->baseUrl() %>/css/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
        <![endif]-->
        <!--[if lt IE 7]>
            <link href="<% $this->baseUrl() %>/css/ie6.css" media="screen, projection" rel="stylesheet" type="text/css" />
        <![endif]-->
        <script src="<% $this->baseUrl() %>/lib/modernizr-2.0.6.min.js"></script>
    </head>
    <body>
        <div id="container">
            <div id="header">
                <header class="page">
                    <hgroup>
                        <h1><a href="<% $this->baseUrl() %>">PHPConf Taiwan <% $year %></a></h1>
                        <h2>台灣 PHP 界的大盛事</h2>
                    </hgroup>
                </header>
                <% partial name="frontend/nav" class="top" %>
            </div>
            <div id="body">
                <div id="main" role="main">
                    <% $this->layout()->content %>
                </div>
                <aside>
                    <section>
                        <h1>贊助</h1>
                        <ul>
                            <% foreach $sponsors as $sponsor %>
                            <li><% $sponsor->name|escape %> - <% $sponsor->supply|escape %></li>
                            <% /foreach %>
                        </ul>
                    </section>
                </aside>
            </div>
            <div id="footer">
                <% partial name="frontend/nav" class="bottom" %>
                <footer class="page">
                    <p class="copyright">&copy;<% $year %> PHPConf.TW</p>
                </footer>
            </div>
        </div> <!--! end of #container -->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="<% $this->baseUrl() %>/lib/jquery-1.6.2.min.js"><\/script>')</script>
        <script src="<% $this->baseUrl() %>/js/phpconf.js"></script>
    </body>
</html>
