<div data-role="navbar" class="custom-icon">
    <ul>
        <li><a href="#announcements" data-icon="custom" data-transition="fade" class="announcements<% if $id === "announcements" %> ui-btn-active ui-state-persist<% /if %>">公告</a></li>
        <li><a href="#sessions" data-icon="custom" data-transition="fade" class="sessions<% if $id === "sessions" %> ui-btn-active ui-state-persist<% /if %>">議程</a></li>
        <li><a href="#location" data-icon="custom" data-transition="fade" class="location<% if $id === "location" %> ui-btn-active ui-state-persist<% /if %>">地點</a></li>
    </ul>
</div><!-- /navbar -->