<!doctype html>
<html class="no-js" lang="zh-TW">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=0;" />
        <link href="http://www.plurk.com/apple-touch-icon.png" rel="apple-touch-icon" />
        <link rel="stylesheet" href="<% $this->baseUrl() %>/css/mobile.css" media="handheld" />
        <title>PHPConf Taiwan <% $year %></title>
    </head>
    <body>
        <div id="container">
            <header class="page">
                <div id="hgroup">
                    <hgroup>
                        <h1><a href="<% $this->baseUrl() %>">PHPConf Taiwan <% $year %></a></h1>
                        <h2><a class="register" href="<% $conference->registrationUrl|escape %>" target="_blank">現在就報名！</a></h2>
                    </hgroup>
                </div>
            </header>
            <% partial name="index/index" %>
            <% partial name="index/sessions" %>
            <% partial name="index/location" %>
        </div>
    </body>
</html>