<div id="sessions">
    <p><a href="<% $this->url(['action' => 'session-edit']) %>">新增</a></p>
    <table>
        <thead>
            <tr>
                <th>主題</th>
                <th>講師</th>
                <th>開始時間</th>
                <th>結束時間</th>
                <th>編輯</th>
            </tr>
        </thead>
        <tbody>
            <% foreach $sessions as $session %>
            <tr>
                <td><% $session->subject|escape %></td>
                <td><% $session->talker|escape %></td>
                <td><% $session->startTime|escape %></td>
                <td><% $session->endTime|escape %></td>
                <td><a href="<% $this->url(['action' => 'session-edit', 'id' => $session->id]) %>">編輯</a></td>
            </tr>
            <% /foreach %>
        </tbody>
    </table>
</div>

