<div id="staffs">
    <table>
        <thead>
            <tr>
                <th>姓名</th>
                <th>工作</th>
                <th>編輯</th>
            </tr>
        </thead>
        <tbody>
            <% foreach $staffs as $staff %>
            <tr>
                <td><% $staff->name|escape %></td>
                <td><% $staff->jobId|escape %></td>
                <td><a href="<% $this->url(['action' => 'staff-edit', 'id' => $staff->id], 'admin') %>">編輯</a></td>
            </tr>
            <% /foreach %>
        </tbody>
    </table>
</div>